export const images = {
    bladeComb: require("../../../assets/images/combs/barberCombWithBlade.jpg"),
    longAfro: require("../../../assets/images/combs/longAfroComb_LE_upscale_balanced_x4.jpg"),
    metalAfro: require("../../../assets/images/combs/metalAfroComb_LE_upscale_balanced_x4.jpg"),
    newMetalTail: require("../../../assets/images/combs/newMetalTailComb_LE_upscale_balanced_x4.jpg"),
    regularAfro: require("../../../assets/images/combs/normalAfroComb_LE_upscale_balanced_x4.jpg"),
    blackBraid: require("../../../assets/images/combs/smallBlackComb_LE_upscale_balanced_x4.jpg"),
    smallHammer: require("../../../assets/images/combs/smallHammerCombBrown_LE_upscale_balanced_x4.jpg"),
    traingleHoleAfro: require("../../../assets/images/combs/traingleHoleAfro_LE_upscale_balanced_x4.jpg"),
    twoTail: require("../../../assets/images/combs/twoTailCombs_LE_upscale_balanced_x4.jpg"),
    umbrella: require("../../../assets/images/combs/umbrellaComb_LE_upscale_balanced_x4.jpg"),
    Subaru: require("../../../assets/images/combs/Subaru.jpg"),
    babiesBrush: require("../../../assets/images/combs/babiesBrush.jpeg"),
    bareFrontMirror: require("../../../assets/images/combs/bareFrontMirror.webp"),
    beltComb: require("../../../assets/images/combs/beltComb.webp"),
    bigBabySetComb: require("../../../assets/images/combs/bigBabySetComb.jpeg"),
    bigWigBrush: require("../../../assets/images/combs/bigWigBrush.jpg"),
    bonnetSleepCap: require("../../../assets/images/combs/bonnetSleepCap.webp"),
    chinaHairDye: require("../../../assets/images/combs/chinaHairDye.avif"),
    fourTail: require("../../../assets/images/combs/fourTail.jpeg"),
    oldMetalTail: require("../../../assets/images/combs/old-metal-tail.png"),
    oneSided: require("../../../assets/images/combs/oneSided.jpeg"),
    smallHammer: require("../../../assets/images/combs/smallHammerMixedColors.jpeg")
};