export const images = {
    bladeComb: require("../../../assets/images/stocks/barberCombWithBlade.jpg"),
    longAfro: require("../../../assets/images/stocks/longAfroComb_LE_upscale_balanced_x4.jpg"),
    metalAfro: require("../../../assets/images/stocks/metalAfroComb_LE_upscale_balanced_x4.jpg"),
    newMetalTail: require("../../../assets/images/stocks/newMetalTailComb_LE_upscale_balanced_x4.jpg"),
    regularAfro: require("../../../assets/images/stocks/normalAfroComb_LE_upscale_balanced_x4.jpg"),
    blackBraid: require("../../../assets/images/stocks/smallBlackComb_LE_upscale_balanced_x4.jpg"),
    smallHammer: require("../../../assets/images/stocks/smallHammerCombBrown_LE_upscale_balanced_x4.jpg"),
    traingleHoleAfro: require("../../../assets/images/stocks/traingleHoleAfro_LE_upscale_balanced_x4.jpg"),
    twoTail: require("../../../assets/images/stocks/twoTailCombs_LE_upscale_balanced_x4.jpg"),
    umbrella: require("../../../assets/images/stocks/umbrellaComb_LE_upscale_balanced_x4.jpg"),
    Subaru: require("../../../assets/images/stocks/Subaru.jpg"),
    babiesBrush: require("../../../assets/images/stocks/babiesBrush.jpeg"),
    bareFrontMirror: require("../../../assets/images/stocks/bareFrontMirror.webp"),
    beltComb: require("../../../assets/images/stocks/beltComb.webp"),
    bigBabySetComb: require("../../../assets/images/stocks/bigBabySetComb.jpeg"),
    bigWigBrush: require("../../../assets/images/stocks/bigWigBrush.jpg"),
    bonnetSleepCap: require("../../../assets/images/stocks/bonnetSleepCap.webp"),
    chinaHairDye: require("../../../assets/images/stocks/chinaHairDye.avif"),
    fourTail: require("../../../assets/images/stocks/fourTail.jpeg"),
    oldMetalTail: require("../../../assets/images/stocks/old-metal-tail.png"),
    oneSided: require("../../../assets/images/stocks/oneSided.jpeg"),
    smallHammer: require("../../../assets/images/stocks/smallHammerMixedColors.jpeg")
};